### ISSUE TITLE
url parse error

### ISSUE THREAD

**Issue by Scrxtchy** [aktavor69/pthbetter#16]
```
~/pthbetter $ ./pthbetter https://passtheheadphones.me/torrents.php?torrentid=275673
Logging in to passtheheadphones ...
Searching for transcode candidates...
You supplied one or more release URLs, ignoring your configuration's media types.
Traceback (most recent call last):
  File "./pthbetter", line 221, in <module>
    main()
  File "./pthbetter", line 123, in main
    [dict(urlparse.parse_qsl(urlparse.urlparse(url).query)) for url in args.release_urls]]
KeyError: 'id'
```

I've also tried `https://passtheheadphones.me/torrents.php?id=151186&torrentid=275673#torrent275673
` which returned similar results, except the KeyError was on `'id'`

**Comment by 2xffwd** [comment]
try with

 https://passtheheadphones.me/torrents.php?id=151186&torrentid=275673

that should be the right url

**Comment by Scrxtchy** [comment]
got a KeyError on `torrent.id`

**Comment by 2xffwd** [comment]
i got this:

pthbetter "https://passtheheadphones.me/torrents.php?id=151186&torrentid=275673"
Logging in to passtheheadphones ...
Searching for transcode candidates...
You supplied one or more release URLs, ignoring your configuration's media types.

Release found: Porter Robinson EP (Japan Limited Edition) (2013)
Release URL: https://passtheheadphones.me/torrents.php?id=151186&torrentid=275673#torrent275673
Formats needed: 


You have to put quotes...pthbetter "url"

**Comment by Scrxtchy** [comment]
lol, thanks 🤦
