### ISSUE TITLE
After creating torrent it is unregistered? Have to add from site manually

### ISSUE THREAD

**Issue by askl56** [aktavor69/pthbetter#5]
Is this intended behaviour? Didn't happen elsewhere this script has been used

**Comment by aktavor69** [comment]
you need to use this mktorrent : https://github.com/Rudde/mktorrent

the regular mktorrent doesnt allow -s flag

**Comment by askl56** [comment]
Same behaviour after doing this... do i need to reboot the server or w/e?

**Comment by aktavor69** [comment]
nop. have you removed the old one ?

do you have the -s flag with this command 

`mktorrent -s`

if not, you need to remove the old one and reinstall the new one.

then, try again this command on pthbetter folder

`sudo python setup.py install`

**Comment by askl56** [comment]
``` ~/apps/app/mktorrent$ mktorrent -s
mktorrent 1.0 (c) 2007, 2009 Emil Renner Berthing

mktorrent: option requires an argument -- 's'
Use -h for help.```

**Comment by askl56** [comment]
Still same error :\

**Comment by aktavor69** [comment]
Sorry, it was "mktorrent -h" but anyway it seems you have the good one.

Try this transcode.py file : http://pastebin.com/017Vn1ue 
Or change with the correct path "mktorrent" at line #345

Then, try with the command : ./pthbetter "url"

Dont forget apply 777 chmod on all files
